esphome:
  name: esp32_test
  platform: ESP32
  board: esp-wrover-kit
  includes:
    - bentel_kyo32.h

wifi:
  ssid: "xxxx"
  password: "xxxx"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32 Test Fallback Hotspot"
    password: "xxxx"

captive_portal:

# Enable logging
logger:
  level: VERBOSE
  baud_rate: 0

# Enable Home Assistant API
api:
  password: "xxxx"

ota:
  password: "xxxx"

uart:
  id: uart_bus
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 9600
  data_bits: 8
  parity: EVEN
  
#time:
#  - platform: homeassistant
#    id: homeassistant_time
#    on_time:
#      # Every 5 minutes
#      - seconds: /5
#        then:
#          - uart.write: [0xF0, 0x04, 0xF0, 0x0A, 0x00, 0xEE]

binary_sensor:
  - platform: custom
    lambda: |-
      auto kyo32 = new Bentel_Kyo32(id(uart_bus));
      App.register_component(kyo32);
      return {kyo32->zona[0], kyo32->zona[1], kyo32->zona[2], kyo32->zona[3], kyo32->zona[4], kyo32->zona[5], kyo32->zona[6], kyo32->zona[7], kyo32->zona[8], kyo32->zona[9], kyo32->zona[10], kyo32->zona[12], kyo32->zona[12], kyo32->zona[13], kyo32->zona[14], kyo32->zona[15]};
    binary_sensors:
      - id: zona_1
        name: "IR Sala"
      - id: zona_2
        name: "Porta Ingresso"
      - id: zona_3
        name: "Finestra Sala"
      - id: zona_4
        name: "Porta Finestra Cucina"
      - id: zona_5
        name: "Finestra Cucina"
      - id: zona_6
        name: "IR Taverna"
      - id: zona_7
        name: "Basculanti Garage"
      - id: zona_8
        name: "Portico"
      - id: zona_9
        name: "IR Camere"
      - id: zona_10
        name: "Finestra Cameretta"
      - id: zona_11
        name: "Finestra Camera Armadio"
      - id: zona_12
        name: "Finestra Camera Matrimoniale"
      - id: zona_13
        name: "Finestra Bagno notte"
      - id: zona_14
        name: "Zona 14  "
      - id: zona_15
        name: "Zona Inserimento"
      - id: zona_16
        name: "Telecamere"
    
